fixtures:
  repositories:
    puppi:
      repo: "https://github.com/example42/puppi.git"
      ref: "v2.1.9"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.0.2"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
  symlinks:
    autoconfig: "#{source_dir}"

