name 'tohuwabohu-autoconfig'
version '1.0.2'
source 'https://github.com/tohuwabohu/puppet-autoconfig.git'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Manage auto-discovery for service clients'
description ''
project_page 'https://github.com/tohuwabohu/puppet-autoconfig'

dependency 'puppetlabs/concat', '1.x'
dependency 'puppetlabs/stdlib', '4.x'
